# Form implementation generated from reading ui file 'интерфейс.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
from PyQt6.QtWidgets import QMessageBox
import math

"""
self.lineEdit   = h
self.lineEdit_2 = T
self.lineEdit_3 = a
self.lineEdit_4 = b
self.lineEdit_5 = c
self.lineEdit_6 = d
"""
xs = [] # массив точек x(t)
x0 = 0
h = 0
T = 0
#Коэффициенты у функции
a = 0
b = 0
c = 0
d = 0


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(597, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 71, 21))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 60, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 71, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 71, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 110, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 150, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 190, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 240, 113, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 0, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 20, 201, 51))
        self.label_8.setStyleSheet("border-image: url(:/newPrefix/func.png);")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/newPrefix/func.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(140, 70, 391, 161))
        self.label_10.setStyleSheet("border-image: url(:/newPrefix/шаг.jpg);")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap(":/newPrefix/шаг.jpg"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 230, 201, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 260, 271, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 597, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Курсовая работа"))
        self.label.setText(_translate("MainWindow", "Введите h"))
        self.label_2.setText(_translate("MainWindow", "Введите T"))
        self.label_3.setText(_translate("MainWindow", "Введите a"))
        self.label_4.setText(_translate("MainWindow", "Введите b"))
        self.label_5.setText(_translate("MainWindow", "Введите c"))
        self.label_6.setText(_translate("MainWindow", "Введите d"))
        self.label_7.setText(_translate("MainWindow", "Функция"))
        self.pushButton_2.setText(_translate("MainWindow", "Построить график x(t)"))
        self.pushButton_3.setText(_translate("MainWindow", "Построить график погрешности"))

    def funcX(self, x):
        """
        Подсчет и возврат значения функции
        :param x: точка
        :return: значение функции
        """""
        return (a * (x ** 2) / (b * (x ** 4) + 4 + math.sin(c * x))) * math.sin((d * x) / 2)

    def graphXt(self):
        """
        Функция для получения точек и построения функций
        """
        """
        self.lineEdit   = h
        self.lineEdit_2 = T
        self.lineEdit_3 = a
        self.lineEdit_4 = b
        self.lineEdit_5 = c
        self.lineEdit_6 = d
        """
        try:
            h = int(self.lineEdit.text())
            T = int(self.lineEdit_2.text())
            a = int(self.lineEdit_3.text())
            b = int(self.lineEdit_4.text())
            c = int(self.lineEdit_5.text())
            d = int(self.lineEdit_6.text())
        except ValueError:
            print("Вы ввели не число в одной из строк")
            dialog = QMessageBox(parent=self, text="Вы ввели не число в одной из строк")
            dialog.setWindowTitle("Ошибка преобразования")
            ret = dialog.exec()

    def graphRunge(self):
        """
        Функция для построения графика
        погрешности методом Рунге
        """
        pass


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):

    def __init__(self):
        super().__init__()
        self.setupUi(self)
        pixmap = QPixmap('func.png')
        pixmap1 = QPixmap('шаг.jpg')
        self.label_8.setPixmap(pixmap)
        self.label_8.setScaledContents(True)
        self.label_10.setPixmap(pixmap1)
        self.label_10.setScaledContents(True)
        self.pushButton_2.clicked.connect(self.graphXt)
        self.pushButton_3.clicked.connect(self.graphRunge)


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    p = MainWindow()
    p.show()
    sys.exit(app.exec())
